//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRailTracker.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iRailTracker.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Services.
        /// </summary>
        internal static string FindServices {
            get {
                return ResourceManager.GetString("FindServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an option to begin..
        /// </summary>
        internal static string HeaderChooseOption {
            get {
                return ResourceManager.GetString("HeaderChooseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Train Journeys.
        /// </summary>
        internal static string LiveTrainJourneys {
            get {
                return ResourceManager.GetString("LiveTrainJourneys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate Nearby Station.
        /// </summary>
        internal static string LocateNearbyStation {
            get {
                return ResourceManager.GetString("LocateNearbyStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a Train Station.
        /// </summary>
        internal static string PickTrainStation {
            get {
                return ResourceManager.GetString("PickTrainStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓ Pull to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Journeys.
        /// </summary>
        internal static string RefreshJourneys {
            get {
                return ResourceManager.GetString("RefreshJourneys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Stations.
        /// </summary>
        internal static string SearchStations {
            get {
                return ResourceManager.GetString("SearchStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a station.
        /// </summary>
        internal static string SelectStationTitle {
            get {
                return ResourceManager.GetString("SelectStationTitle", resourceCulture);
            }
        }
    }
}
